#!/bin/bash
# Erix Setup Version 0.1.0 -- Setup-Routine für Ubuntu 20.04 LTS
# Copyright (C) 2020 Eric Haberstroh <gpg@erixpage.de>

# Dieses Programm ist Freie Software: Sie können es unter den Bedingungen
# der GNU General Public License, wie von der Free Software Foundation,
# Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
# veröffentlichten Version, weiter verteilen und/oder modifizieren.

# Dieses Programm wird in der Hoffnung bereitgestellt, dass es nützlich sein wird, jedoch
# OHNE JEDE GEWÄHR; sogar ohne die implizite
# Gewähr der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
# Siehe die GNU General Public License für weitere Einzelheiten.

# Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
# Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>.

source $(dirname $0)/common.sh

## Begrüßungsnachricht
echo "Erix Essentials Backup $VERSION -- Wichtige Dateien sichern"
echo ""
echo "Copyright (C) 2020 Eric Haberstroh <gpg@erixpage.de>"
echo ""
echo "Dieses Programm ist Freie Software: Sie können es unter den Bedingungen"
echo "der GNU General Public License, wie von der Free Software Foundation,"
echo "Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren"
echo "veröffentlichten Version, weiter verteilen und/oder modifizieren."
echo ""
echo "Dieses Programm wird in der Hoffnung bereitgestellt, dass es nützlich sein wird, jedoch"
echo "OHNE JEDE GEWÄHR; sogar ohne die implizite"
echo "Gewähr der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK."
echo "Siehe die GNU General Public License für weitere Einzelheiten."
echo ""
echo "Sie sollten eine Kopie der GNU General Public License zusammen mit diesem"
echo "Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>."
echo ""

## Backuplauf starten
test -e essentials.tar.gz.gpg && fatal "Das Zielarchiv essentials.tar.gz.gpg existiert bereits."
gpg --export-ownertrust >ownertrust.txt
tar czv ~/.ssh/{authorized_keys,known_hosts} ~/.gnupg/{pubring,secring}.gpg ownertrust.txt | gpg --symmetric >essentials.tar.gz.gpg
rm ownertrust.txt
test $? -eq 0 && success "Essentials wurden erfolgreich gesichert. Die Datei essentials.tar.gz.gpg sollte an einen sicheren Ort verschoben werden."
