#!/bin/bash
# Erix Setup Version 0.1.0 -- Setup-Routine für Ubuntu 20.04 LTS
# Copyright (C) 2020 Eric Haberstroh <gpg@erixpage.de>

# Dieses Programm ist Freie Software: Sie können es unter den Bedingungen
# der GNU General Public License, wie von der Free Software Foundation,
# Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren
# veröffentlichten Version, weiter verteilen und/oder modifizieren.

# Dieses Programm wird in der Hoffnung bereitgestellt, dass es nützlich sein wird, jedoch
# OHNE JEDE GEWÄHR; sogar ohne die implizite
# Gewähr der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK.
# Siehe die GNU General Public License für weitere Einzelheiten.

# Sie sollten eine Kopie der GNU General Public License zusammen mit diesem
# Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>.

source $(dirname $0)/common.sh

## Begrüßungsnachricht
echo "Erix Setup Version $VERSION -- Setup-Routine für Ubuntu 20.04 LTS"
echo ""
echo "Copyright (C) 2020 Eric Haberstroh <gpg@erixpage.de>"
echo ""
echo "Dieses Programm ist Freie Software: Sie können es unter den Bedingungen"
echo "der GNU General Public License, wie von der Free Software Foundation,"
echo "Version 3 der Lizenz oder (nach Ihrer Wahl) jeder neueren"
echo "veröffentlichten Version, weiter verteilen und/oder modifizieren."
echo ""
echo "Dieses Programm wird in der Hoffnung bereitgestellt, dass es nützlich sein wird, jedoch"
echo "OHNE JEDE GEWÄHR; sogar ohne die implizite"
echo "Gewähr der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK."
echo "Siehe die GNU General Public License für weitere Einzelheiten."
echo ""
echo "Sie sollten eine Kopie der GNU General Public License zusammen mit diesem"
echo "Programm erhalten haben. Wenn nicht, siehe <https://www.gnu.org/licenses/>."
echo ""

## Einstellungen laden
test -r settings || fatal "Die Einstellungen aus der Datei settings können nicht geladen werden."
source settings

## Prüfen, ob alle notwendigen Variablen gesetzt sind
vars="DESIRED_APT DESIRED_SNAP DESIRED_DIRS WORKGROUP"

for var in $vars; do
    test -n "${!var}" || fatal "Die Variable $var wird in settings nicht definiert, wird aber zwingend benötigt."
done

## Installation gewünschter APT-Pakete
notice "Die folgenden Pakete werden nun mittels APT installiert:"
echo $DESIRED_APT
echo ""
cont_skip_abort
if [[ $? -eq 0 ]]; then
    sudo apt install $DESIRED_APT
fi

## Installation gewünschter Snaps
notice "Die folgenden Programme werden nun als Snap installiert:"
echo $DESIRED_SNAP
echo ""
cont_skip_abort
if [[ $? -eq 0 ]]; then
    for snap in $DESIRED_SNAP; do
        sudo snap install $snap
        if [[ $? -ne 0 ]]; then
            warn "Die Installation scheint fehlgeschlagen zu sein. Versuch mit Option --classic wird unternommen."
            sudo snap install --classic $snap
        fi
    done
fi

## Google Chrome herunterladen und installieren
notice "Google Chrome wird als Debian-Paket heruntergeladen und installiert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    pushd /tmp
    wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    sudo dpkg -i google-chrome-stable_current_amd64.deb
    rm google-chrome-stable_current_amd64.deb
    popd
fi

## NUR AENEAS: Mountpoints anlegen
if [[ "$(hostname)" = "aeneas" ]]; then
    notice "(aeneas): Die Mountpoints /EXTERN, /EXTWIN und /WINDOWS werden angelegt:"
    notice "/EXTERN  = ext4-Partition auf der externen Festplatte"
    notice "/EXTWIN  = NTFS-Partition auf der externen Festplatte"
    notice "/WINDOWS = NTFS-Partition auf der internen Festplatte"
    notice "/etc/fstab wird konfiguriert, diese Partitionen beim Systemstart einzuhängen, und sie werden sofort gemountet."
    cont_skip_abort
    if [[ $? -eq 0 ]]; then
        sudo mkdir /EXTERN /EXTWIN /WINDOWS
        echo '/dev/disk/by-id/usb-WD_Elements_10A8_575841314136343359483933-0:0-part1 /EXTERN auto nosuid,nodev,nofail,x-gvfs-show 0 0' | sudo tee -a /etc/fstab
        echo '/dev/disk/by-id/usb-WD_Elements_10A8_575841314136343359483933-0:0-part2 /EXTWIN auto nosuid,nodev,nofail,x-gvfs-show 0 0' | sudo tee -a /etc/fstab
        echo '/dev/disk/by-uuid/BAA0E7E2A0E7A35D /WINDOWS auto nosuid,nodev,nofail,x-gvfs-show 0 0' | sudo tee -a /etc/fstab
        sudo mount /EXTERN
        sudo mount /EXTWIN
        sudo mount /WINDOWS
    fi
fi

## LAMP-Setup
notice "Es wird nun mysql_secure_installation ausgeführt, um MariaDB zu konfigurieren."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    sudo mysql_secure_installation
fi

notice "Composer wird installiert und ein Self-Update durchgeführt."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    pushd /tmp
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    sudo mv -v composer.phar /usr/local/bin/composer
    sudo chown -v root:root /usr/local/bin/composer
    sudo composer self-update
    popd
fi

notice "NodeJS Version ~12 wird als Snap installiert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    sudo snap install node --classic --channel=12
fi

## Tastaturkürzel
notice "Das Tastaturkürzel Strg + Alt + C für den Taschenrechner wird eingerichtet."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    gsettings set "org.gnome.settings-daemon.plugins.media-keys" "calculator" "['<Primary><Alt>c']"
fi

## Bildschirmabschaltung
notice "Die Bildschirmabschaltung bei Untätigkeit wird auf 15 Minuten eingestellt."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    gsettings set "org.gnome.desktop.session" "idle-delay" 900
fi

## Dash-To-Dock
notice "Die Größe der Icons im Dock wird nun auf 24 Pixel reduziert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    gsettings set "org.gnome.shell.extensions.dash-to-dock" "dash-max-icon-size" 24
fi

## GNOME Terminal
notice "Die Standardgröße eines Terminalfensters wird nun auf 125x40 Zeilen gesetzt."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
    profile=${profile:1:-1}
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 125
    gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-rows 40
fi

notice "Die Taste F10 für den Menüaufruf in Terminalfenstern wird deaktiviert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    gsettings set "org.gnome.Terminal.Legacy.Settings" "menu-accelerator-enabled" false
fi

## Essentials-Backup wiederherstellen
notice "Das Archiv essentials.tar.gz wird in $HOME entpackt."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    dir=$(pwd)
    pushd $HOME
    tar xzvf $dir/essentials.tar.gz
    popd
fi

## Verzeichnisse in $HOME anlegen
notice "Die folgenden Verzeichnisse werden in $HOME angelegt:"
echo $DESIRED_DIRS
cont_skip_abort
if [[ $? -eq 0 ]]; then
    pushd $HOME
    for d in $DESIRED_DIRS; do
        mkdir -v $d
    done
    popd
fi

## Samba / Shares
if [[ -e /etc/samba/smb.conf ]]; then
    notice "Es wird ein SMB-Passwort für den Benutzer $USER vergeben."
    cont_skip_abort
    if [[ $? -eq 0 ]]; then
        sudo smbpasswd -a $USER
    fi

    notice "Samba wird für die Verwendung der Arbeitsgruppe $WORKGROUP konfiguriert."
    cont_skip_abort
    if [[ $? -eq 0 ]]; then
        sudo cp -v /etc/samba/smb.conf{,.SKP}
        sudo sed -i "s/WORKGROUP/$WORKGROUP/" /etc/samba/smb.conf
    fi

    notice "Die folgenden User-Shares werden angelegt:"
    notice "  - ${USER}_docs   -> $HOME/Dokumente"
    notice "  - ${USER}_music  -> $HOME/Musik"
    notice "  - ${USER}_public -> $HOME/Öffentlich"
    notice "  - ${USER}_videos -> $HOME/Videos"
    cont_skip_abort
    if [[ $? -eq 0 ]]; then
        domainsid=$(sudo net getlocalsid | cut -d':' -f2 | sed "s/ //g")
        usersid="$domainsid-$UID"
        (sudo cat <<EOF
#VERSION 2
path=/home/eric/Dokumente
comment=
usershare_acl=S-1-1-0:R,${usersid}:F
guest_ok=n
sharename=eric_docs
EOF
        )>/var/lib/samba/usershares/eric_docs
        (sudo cat <<EOF
#VERSION 2
path=/home/eric/Musik
comment=
usershare_acl=S-1-1-0:R,${usersid}:F
guest_ok=n
sharename=eric_music
EOF
        )>/var/lib/samba/usershares/eric_music
        (sudo cat <<EOF
#VERSION 2
path=/home/eric/Öffentlich
comment=
usershare_acl=S-1-1-0:F
guest_ok=n
sharename=eric_public
EOF
        )>/var/lib/samba/usershares/eric_public
        (sudo cat <<EOF
#VERSION 2
path=/home/eric/Videos
comment=
usershare_acl=S-1-1-0:R,${usersid}:F
guest_ok=n
sharename=eric_videos
EOF
        )>/var/lib/samba/usershares/eric_videos
    fi
else
    warn "Samba ist nicht installiert. Wenn Sie den Teil dieses Programms, mit dem Samba konfiguriert wird,"
    warn "ausführen möchten, fügen Sie samba zur Variable DESIRED_APT in settings hinzu und führen Sie das"
    warn "Setup-Programm erneut aus."
fi

## Oh My Zsh
notice "Oh My Zsh wird geklont und installiert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    pushd $HOME
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    rm .zshrc
    popd
fi

## Dotfiles
notice "Persönliche Dotfiles werden geklont und installiert."
cont_skip_abort
if [[ $? -eq 0 ]]; then
    pushd $HOME/Code
    git clone https://github.com/pille1842/dotfiles
    pushd dotfiles
    ./install.sh
    popd
    popd
fi

success "Setup wurde erfolgreich abgeschlossen. Ein Logout wird dringend empfohlen."
